[build]
  publish = "dist/bug-netlify-angular-ssr/browser"
  command = "ng build"
  functions = "netlify/functions"

[[redirects]]
  from = "/de/*"
  to = "/de/index.html"
  status = 200

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/de/index.html"
  status = 200
